/*.$file${../qm_generated::{{ cookiecutter.ao_name }}_sm.c} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/
/*
* Model: {{ cookiecutter.ao_name }}_qpn_pio.qm
* File:  ${../qm_generated::{{ cookiecutter.ao_name }}_sm.c}
*
* This code has been generated by QM 5.1.3 <www.state-machine.com/qm/>.
* DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
*
* This program is open source software: you can redistribute it and/or
* modify it under the terms of the GNU General Public License as published
* by the Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but
* WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
* or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
* for more details.
*/
/*.$endhead${../qm_generated::{{ cookiecutter.ao_name }}_sm.c} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/
#include "{{ cookiecutter.ao_name }}_sm.h"
#include "bsp.h"
#include "app/{{ cookiecutter.ao_name }}_helpers.h"

/*.$skip${QP_VERSION} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/
/*. Check for the minimum required QP version */
#if (QP_VERSION < 690U) || (QP_VERSION != ((QP_RELEASE^4294967295U) % 0x3E8U))
#error qpn version 6.9.0 or higher required
#endif
/*.$endskip${QP_VERSION} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/
/*.$define${AOs::{{ cookiecutter.ao_name | title}}} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/
/*.${AOs::{{ cookiecutter.ao_name | title}}} ..........................................................*/
/*.${AOs::{{ cookiecutter.ao_name | title}}::SM} ......................................................*/
QState {{ cookiecutter.ao_name | title}}_initial({{ cookiecutter.ao_name | title}} * const me) {
    /*.${AOs::{{ cookiecutter.ao_name | title}}::SM::initial} */
    {{ cookiecutter.ao_name | title}}_armTimeout((QActive *) me);
    return Q_TRAN(&{{ cookiecutter.ao_name | title}}_off);
}
/*.${AOs::{{ cookiecutter.ao_name | title}}::SM::off} .................................................*/
QState {{ cookiecutter.ao_name | title}}_off({{ cookiecutter.ao_name | title}} * const me) {
    QState status_;
    switch (Q_SIG(me)) {
        /*.${AOs::{{ cookiecutter.ao_name | title}}::SM::off} */
        case Q_ENTRY_SIG: {
            BSP_ledOff();
            status_ = Q_HANDLED();
            break;
        }
        /*.${AOs::{{ cookiecutter.ao_name | title}}::SM::off::Q_TIMEOUT} */
        case Q_TIMEOUT_SIG: {
            status_ = Q_TRAN(&{{ cookiecutter.ao_name | title}}_on);
            break;
        }
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}
/*.${AOs::{{ cookiecutter.ao_name | title}}::SM::on} ..................................................*/
QState {{ cookiecutter.ao_name | title}}_on({{ cookiecutter.ao_name | title}} * const me) {
    QState status_;
    switch (Q_SIG(me)) {
        /*.${AOs::{{ cookiecutter.ao_name | title}}::SM::on} */
        case Q_ENTRY_SIG: {
            BSP_ledOn();
            status_ = Q_HANDLED();
            break;
        }
        /*.${AOs::{{ cookiecutter.ao_name | title}}::SM::on::Q_TIMEOUT} */
        case Q_TIMEOUT_SIG: {
            status_ = Q_TRAN(&{{ cookiecutter.ao_name | title}}_off);
            break;
        }
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}
/*.$enddef${AOs::{{ cookiecutter.ao_name | title}}} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/
