/*.$file${../qm_generated::{{ cookiecutter.ao_name }}_sm.h} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/
/*
* Model: {{ cookiecutter.ao_name }}_qpn_pio.qm
* File:  ${../qm_generated::{{ cookiecutter.ao_name }}_sm.h}
*
* This code has been generated by QM 5.1.3 <www.state-machine.com/qm/>.
* DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
*
* This program is open source software: you can redistribute it and/or
* modify it under the terms of the GNU General Public License as published
* by the Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but
* WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
* or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
* for more details.
*/
/*.$endhead${../qm_generated::{{ cookiecutter.ao_name }}_sm.h} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/
#ifndef {{ cookiecutter.project_name | upper | replace("_", "") }}_SM_H
#define {{ cookiecutter.project_name | upper | replace("_", "") }}_SM_H

#ifdef __cplusplus
extern "C" {
#endif

#include "qpn.h"
#include "signals.h"
#include "constants.h"

/*.$declare${AOs::{{ cookiecutter.ao_name | title}}} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/
/*.${AOs::{{ cookiecutter.ao_name | title}}} ..........................................................*/
typedef struct {{ cookiecutter.ao_name | title}} {
/* protected: */
    QActive super;
} {{ cookiecutter.ao_name | title}};

/* protected: */
QState {{ cookiecutter.ao_name | title}}_initial({{ cookiecutter.ao_name | title}} * const me);
QState {{ cookiecutter.ao_name | title}}_off({{ cookiecutter.ao_name | title}} * const me);
QState {{ cookiecutter.ao_name | title}}_on({{ cookiecutter.ao_name | title}} * const me);
/*.$enddecl${AOs::{{ cookiecutter.ao_name | title}}} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/

#ifdef __cplusplus
}
#endif

#endif
